version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ifode_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Banco.sql:/docker-entrypoint-initdb.d/Banco.sql
    networks:
      - ifode_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ifode_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=postgres
    networks:
      - ifode_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  ifode_network:
    driver: bridge